
exec-once = swww-daemon
exec-once = quickshell
exec-once = eww daemon

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

env = XDG_CURRENT_DESKTOP,wlroots
env = XDG_SESSION_TYPE,wayland

env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_SIZE,24

exec = gsettings set org.gnome.desktop.interface gtk-theme "AdwNew"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

exec = gsettings set org.gnome.desktop.interface cursor-theme 'catppuccin-mocha-dark-cursors'
exec = gsettings set org.gnome.desktop.interface cursor-size 24
