hl.config({ autogenerated = false })

local configDir = (os.getenv("HOME") or "") .. "/.config/hypr"
package.path = configDir .. "/?.lua;" .. configDir .. "/?/init.lua;" .. package.path

require("config.monitors")
require("config.workspaces")
require("config.env")
require("config.input")
require("config.theme")
require("config.glass")
require("config.animations")
require("config.layout")
require("config.rules")
require("config.autostart")

require("binds")
